approvedGitRepositories:
  - '**'

cacheFolder: ./node_modules/.yarn/cache

enableScripts: true

installStatePath: ./node_modules/.yarn/install-state.gz

nodeLinker: node-modules

npmMinimalAgeGate: 0

patchFolder: ./node_modules/.yarn/patches

pnpUnpluggedFolder: ./node_modules/.yarn/unplugged

virtualFolder: ./node_modules/.yarn/__virtual__
